### PR TITLE
Add initial support for tswilliamson's utils

### PR DESCRIPTION
**Pull request by dr-carlos**
This PR implements tswilliamson's splitting of toolchain/prizm_rules into toolchain/base_rules and toolchain/prizm_rules, and adds toolchain/util_rules (such that tswilliamson's utils/ folder can be added).

### CODE REVIEW

**Comment by dr-carlos** [comment]
I have also:
- Added tswilliamson's fxcg/tmu.h (as this is minor so seems pointless being in its own PR).
- Added tswilliamson's getDeviceType function. This is in fxcg/display.h as it was originally put there, but it might make sense somewhere else (fxcg/misc.h?)
- Added -DTARGET_PRIZM=1 to the prizm_rules file such that TARGET_PRIZM is automatically defined, allowing getDeviceType and other functions to work automatically. Note that this can be overridden by the user as it is defined before CFLAGS or CXXFLAGS are used.

**Comment by dr-carlos** [comment]
Any updates on this PR?

**Comment by tari** [comment]
I guess there's nothing controversial in here, but what's the benefit of splitting some things into `util_rules`? It looks like the only difference is supporting more source types (why not add those to the base ones?) and adding `TARGET_PRIZM` (why can't that also be enabled for utils?).

**Comment by dr-carlos** [comment]
> I guess there's nothing controversial in here, but what's the benefit of splitting some things into `util_rules`? It looks like the only difference is supporting more source types (why not add those to the base ones?) and adding `TARGET_PRIZM` (why can't that also be enabled for utils?).

You have a good point. I've removed util_rules and combined base_rules and prizm_rules.
I've went and changed util_rules to prizm_rules in all of the other branches.

**Pull request merged**
